# Copy this file to secrets.yaml and replace placeholder values
# kubectl create secret generic microservices-secrets --from-file=secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  JWT_SECRET: 'CHANGE_THIS_TO_A_SECURE_SECRET'
  DATABASE_URL: 'postgresql://USER:PASSWORD@postgres.microservices.svc.cluster.local:5432/microservices?schema=public'
